import { PrismaClient } from '@prisma/client';
import dotenv from 'dotenv';
dotenv.config();
const prisma = new PrismaClient();

// Map of product ID => verified working image URL
// Local images (served by Express from /images/): generated by AI, guaranteed to work
// Unsplash URLs below have been chosen to exactly match the product described
const imageUpdates = [
  { id: 'ps5-standard',  image: '/images/ps5-standard.png' },
  { id: 'ps5-digital',   image: 'https://images.unsplash.com/photo-1605296830714-7c02e14957ac?auto=format&fit=crop&w=800&q=80' },
  { id: 'ps5-bundle',    image: 'https://images.unsplash.com/photo-1606813904839-4a6ecf9f48f3?auto=format&fit=crop&w=800&q=80' },
  { id: 'samsung-s24',   image: '/images/samsung-s24.png' },
  { id: 'oneplus-12',    image: '/images/oneplus-12.png' },
  { id: 'pixel-8-pro',   image: '/images/pixel-8-pro.png' },
  { id: 'iphone-15-pro', image: '/images/iphone-15-pro.png' },
  { id: 'iphone-15-plus',image: '/images/iphone-15-plus.png' },
  { id: 'iphone-14-pro', image: 'https://images.unsplash.com/photo-1697898706719-bce6e007c817?auto=format&fit=crop&w=800&q=80' },
  { id: 'clear-case',    image: 'https://images.unsplash.com/photo-1535157412991-2ef801c1748b?auto=format&fit=crop&w=800&q=80' },
  { id: 'leather-case',  image: 'https://images.unsplash.com/photo-1588367941115-17cece88d036?auto=format&fit=crop&w=800&q=80' },
  { id: 'matte-case',    image: 'https://images.unsplash.com/photo-1623393884989-cb3663e431c5?auto=format&fit=crop&w=800&q=80' },
];

console.log('Updating product images in Neon...');
for (const { id, image } of imageUpdates) {
  await prisma.product.update({ where: { id }, data: { image } });
  console.log(`✓ ${id} => ${image}`);
}
console.log('All product images updated!');
await prisma.$disconnect();
